version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jorimusic
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FLYWAY_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_CLEAN_DISABLED=false
      - FLYWAY_LOCATIONS=filesystem:/tmp/migrations
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - downloader.service.url=http://downloader:5000
    volumes:
      - /home/joe/JoriMusic_Library:/app/music

  downloader:
    build: ./downloader
    ports:
      - "5000:5000"
    volumes:
      - /home/joe/JoriMusic_Library:/app/music

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run web

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
