spring.datasource.username=jorimusic
spring.datasource.password=jorimusic
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
debug=true
spring.flyway.cleanDisabled=false
logging.level.com.jorimusic.backend.security.JwtTokenProvider=TRACE


jwt.expiration=86400000

music.storage.path=/app/music
downloader.service.url=http://downloader:5000
