spring.datasource.url=jdbc:postgresql://localhost:5432/jorimusic
spring.datasource.username=jorimusic
spring.datasource.password=jorimusic
spring.jpa.hibernate.ddl-auto=update

jwt.secret=OzOK8ZLeM4ECus1gvQeFnwdS3kcM3y2A
jwt.expiration=86400000

music.storage.path=/app/music
downloader.service.url=http://downloader:5000
